#!/usr/bin/env bash
exec &> >(tee -a $HOME/.dotfile-install.log)
set -e
set -x

CONFIGS="install.conf.yaml"

case "$(uname -s)" in
    Darwin)
        CONFIGS+=("mac.conf.yaml")
        ;;
esac

#CONFIGS+=("post.conf.yaml")

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

for CONFIG in "${CONFIGS[@]}"; do
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"
done
