#!/usr/bin/env zsh

# Completions
fpath=($DOTFILES/zsh/plugins $fpath)

# NAVIGATION
setopt AUTO_CD              # Go to folder path without using cd.
setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.
setopt CORRECT              # Spelling correction
setopt CDABLE_VARS          # Change directory to a path stored in a variable.
setopt EXTENDED_GLOB        # Use extended globbing syntax.

# HISTORY
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

# COMPLETION
setopt ALWAYS_TO_END
setopt COMPLETE_IN_WORD

# Aliases
source $DOTFILES/aliases/aliases

# NVM
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Command Completion
source $DOTFILES/zsh/completion.zsh

# Auto Suggestions
source $DOTFILES/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# History substring search
source $DOTFILES/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

# Make less handle binaries better
if [ -f ${HOMEBREW_PREFIX}/bin/lesspipe.sh ]
then
    export LESSOPEN="|${HOMEBREW_PREFIX}/bin/lesspipe.sh %s"
fi

# Delete a given line number in the known_hosts file.
knownrm() {
 re='^[0-9]+$'
 if ! [[ $1 =~ $re ]] ; then
   echo "error: line number missing" >&2;
 else
   sed -i '' "$1d" ~/.ssh/known_hosts
 fi
}

# Flush DNS cache
flushdns() {
  sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder
}

# figurine
if [ -f ~/go/bin/figurine ]
then
  echo ""
  ~/go/bin/figurine -f 3d.flf $(hostname)
  echo ""
fi

# fzf
test -e "$HOMEBREW_PREFIX/bin/fzf" && source <(fzf --zsh)

# zoxide
test -e "$HOMEBREW_PREFIX/bin/zoxide" && eval "$(zoxide init zsh)"

# command-not-found
HB_CNF_HANDLER="$(brew --repository)/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
if [ -f "$HB_CNF_HANDLER" ]; then
source "$HB_CNF_HANDLER";
fi

# Path
export PATH=~/.local/bin:~/bin:$PATH

# iTerm
test -e "$HOME/.iterm2_shell_integration.zsh" && source "$HOME/.iterm2_shell_integration.zsh"

# Window Title
source $DOTFILES/zsh/plugins/zsh-window-title/zsh-window-title.zsh

# Prompt
test -e "$HOMEBREW_PREFIX/bin/starship" && eval "$(starship init zsh)"